# -*- coding: utf-8 -*-
"""Challenge_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5jFg_wslGcT12vfa0onpyyoHvnvkeHM
"""

nom = "Karim"
prenom = "Ben Ali"
notes = [12, 15, 9]
total = 0
nombre_notes = 0

for note in notes:
    total += note
    nombre_notes += 1

moyenne = total / nombre_notes
print(f"Nom      : {nom}")
print(f"Prénom   : {prenom}")
print(f"Notes    : {notes}")
print(f"Moyenne  : {moyenne:>6.2f}/20")

nom = input("Entrez votre nom : ")
prenom = input("Entrez votre prénom : ")
notes = []

for i in range(3):
    note = input(f"Entrez la note {i + 1} : ")

    if note.replace(".", "", 1).isdigit():
        note = float(note)
        notes.append(note)
    else:
        print("Erreur : la note doit être un nombre.")

def calculer_moyenne(notes):
  if not notes:
    print("Attention : aucune note fournie.")
    return 0
  return sum(notes) / len(notes)

def appreciation(moyenne):
    if moyenne < 10:
        return "Insuffisant"
    elif moyenne < 12:
        return "Passable"
    elif moyenne < 16:
        return "Bien"
    else:
        return "Très bien"

calculer_moyenne(notes = [12, 15, 9])

valeurs_test = [9.9, 10.0, 11.9, 12.0, 15.9, 16.0, 20.0]
for valeur in valeurs_test:
  print(f"{valeur:>6.2f} : {appreciation(valeur)}")

etudiants = [{"nom": "Karim", "notes": [12, 15, 9]}, {"nom": "Sara", "notes": [18, 17, 16]}, {"nom": "Lina", "notes": [6, 8, 5]},]

for etudiant in etudiants:
    moyenne_etudiant = calculer_moyenne(etudiant['notes'])
    mention_etudiant = appreciation(moyenne_etudiant)
    print(f"Nom      : {etudiant['nom']}")
    print(f"Moyenne  : {moyenne_etudiant:>6.2f}/20")
    print(f"Mention  : {mention_etudiant}")
    print("--------------------")

meilleure_moyenne = -1
meilleur_etudiant = ""
pire_moyenne = 21
pire_etudiant = ""

for etudiant in etudiants:
    moyenne_etudiant = calculer_moyenne(etudiant['notes'])

    if moyenne_etudiant > meilleure_moyenne:
        meilleure_moyenne = moyenne_etudiant
        meilleur_etudiant = etudiant['nom']

    if moyenne_etudiant < pire_moyenne:
        pire_moyenne = moyenne_etudiant
        pire_etudiant = etudiant['nom']

print(f"Le meilleur étudiant est {meilleur_etudiant} avec une moyenne de {meilleure_moyenne:.2f}/20")
print(f"Le moins bon étudiant est {pire_etudiant} avec une moyenne de {pire_moyenne:.2f}/20")

def calculer_moyenne_ponderee(notes, coefficients):
    if len(notes) != len(coefficients):
        print("Erreur: Le nombre de notes doit correspondre au nombre de coefficients.")
        return None

    somme_produits = sum(note * coeff for note, coeff in zip(notes, coefficients))
    somme_coefficients = sum(coefficients)

    if somme_coefficients == 0:
        print("Erreur: La somme des coefficients est zéro, impossible de calculer la moyenne pondérée.")
        return None

    return somme_produits / somme_coefficients

notes = [14, 10, 18] # Maths, Francais, Sport
coefficients = [3, 2, 1]
moyenne_p = calculer_moyenne_ponderee(notes, coefficients)

if moyenne_p is not None:
    print(f"Moyenne pondérée : {moyenne_p:.2f}/20")

def moyenne_groupe(etudiants):
    total_moyennes = 0
    nombre_etudiants = 0

    for etudiant in etudiants:
        if etudiant['notes']:
            total_moyennes += calculer_moyenne(etudiant['notes'])
            nombre_etudiants += 1

    if nombre_etudiants == 0:
        return 0

    return total_moyennes / nombre_etudiants



etudiants = [
{"nom": "Karim", "notes": [12, 15, 9]},
{"nom": "Sara", "notes": [18, 17, 16]},
{"nom": "Lina", "notes": [6, 8, 5]},
]
moyenne_generale_classe = moyenne_groupe(etudiants)
print(f"La moyenne générale de la classe est : {moyenne_generale_classe:.2f}/20")

def somme_recursive(notes):
    if not notes:
        return 0
    else:
        return notes[0] + somme_recursive(notes[1:])

notes_pour_somme = [12, 15, 9, 18]
resultat_somme = somme_recursive(notes_pour_somme)
print(f"La somme récursive des notes {notes_pour_somme} est : {resultat_somme}")

resultats = {}
for etudiant in etudiants:
    nom_etudiant = etudiant['nom']
    moyenne = calculer_moyenne(etudiant['notes'])
    mention = appreciation(moyenne)
    resultats[nom_etudiant] = {"moyenne": round(moyenne, 1), "mention": mention}

print("Dictionnaire des résultats :")
print(resultats)

etudiants_classes = sorted(resultats.items(), key=lambda item: item[1]['moyenne'], reverse=True)
print("\nClassement des étudiants par moyenne décroissante :")
for nom, data in etudiants_classes:
    print(f"- {nom} : {data['moyenne']:.1f}/20 ({data['mention']})")

etudiants_en_echec = []
for nom, data in resultats.items():
    if data['moyenne'] < 10:
        etudiants_en_echec.append((nom, data['moyenne']))

print("\nÉtudiants en échec (moyenne < 10) :")
print(etudiants_en_echec)

from collections import defaultdict

regroupement_par_mention = defaultdict(list)
for nom, data in resultats.items():
    regroupement_par_mention[data['mention']].append(nom)

print("\nRegroupement des étudiants par mention :")
print(dict(regroupement_par_mention))

noms_test = ["Karim", "Sara", "Lina", "Karim"]
if len(noms_test) != len(set(noms_test)):
    print(f"Attention, il y a des doublons dans la liste {noms_test} !")
else:
    print(f"Aucun doublon n'a été détecté dans la liste {noms_test}.")

groupe_a = {
    "Karim": {"moyenne": 12.0, "mention": "Bien"},
}
groupe_b = {
    "Karim": {"moyenne": 15.0, "mention": "Bien"},
    "Sara": {"moyenne": 17.0, "mention": "Tres bien"},
}

def fusionner_groupes(groupe1, groupe2):
    groupe_fusionne = dict(groupe1)
    conflits = []

    for nom, data2 in groupe2.items():
        if nom in groupe_fusionne:
            conflits.append(f"Conflit pour {nom}: les données de groupe_b ne sont pas fusionnées pour éviter l'écrasement. Données de groupe_a conservées.")
        else:
            groupe_fusionne[nom] = data2

    return groupe_fusionne, conflits

groupe_fusionne, conflits = fusionner_groupes(groupe_a, groupe_b)

print("\nGroupe A :", groupe_a)
print("Groupe B :", groupe_b)
print("\nGroupe fusionné :", groupe_fusionne)
if conflits:
    print("Conflits détectés lors de la fusion :")
    for conflit in conflits:
        print(f"- {conflit}")
else:
    print("Aucun conflit détecté lors de la fusion.")

